server:
  port: 8080
spring:
  application:
    name: "customer"
  datasource:
    url: "jdbc:h2:file:~/customer;AUTO_SERVER=true"
    driver-class-name: "org.h2.Driver"
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "accounts"
    description: "Eazy Bank Customer Application"
    version: "1.0.0"

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

axon:
  eventhandling:
    processors:
      customer-group:
        mode: subscribing
  axonserver:
    servers: localhost:8124


# customer-group: a name for a group of event handlers (@EventHandler methods)
# So in this case, all handlers in this group are processed together using one thread
#
# mode:
#   - subscribing: handles events immediately in memory (synchronous)
#       → Fast and simple, for single-instance setups
#       → If an error happens in a projection, the whole event is rejected right away (can crash the app)
#
#   - tracking: reads events from the event store and handles them independently (asynchronous)
#       → Good for scaling, replaying, and distributed apps
#       → If an error happens, the processor can retry, skip, or be configured to stop — without crashing the app so may read unupdated data